### ISSUE TITLE
Crash on Dialy not name format change

### ISSUE THREAD

**Issue by ElsaTam** [Erallie/diarian#2]
The plugin seems to crash when I refresh the calendar after changing the format of my daily notes, if I already had existing notes.

## Expected Behavior
When refreshing the calendar after a change of daily notes format, I would expect to see the calendar up to date with the new format, without trying to fetch unexisting notes.

## Current Behavior
The plugin tries to find old daily notes with the new format, and can't find them, making the whole plugin crash.

## Possible Solution
Somewhere in the code, a check "if null" is probably missing and an attemps is made to get inexisting data. Maybe either add more checks, or clear and redo the whole list of daily notes everytime the refresh is asked by the user.

## Steps to Reproduce
1. Create a Daily Note with a certain name template
2. Change the template name
3. Refresh the calendar --> the plugin crashed

## Detailed Error
The following warning appears several times in the console (might be less than the number of notes though, I had 36 notes and the warning showed up for only 3 notes)
```
plugin:diarian:30570 [Diarian] warning: Could not get any notes with the date 2024-08-01T-03-43-00.
    at printToConsole (plugin:diarian:30545:11)
    at getNoteByMoment (plugin:diarian:30668:5)
    at imagePath (plugin:diarian:41228:26)
    at eval (plugin:diarian:41243:5)
    at commitHookEffectListMount (plugin:diarian:18851:34)
    at commitPassiveMountOnFiber (plugin:diarian:20104:17)
    at commitPassiveMountEffects_complete (plugin:diarian:20072:17)
    at commitPassiveMountEffects_begin (plugin:diarian:20062:15)
    at commitPassiveMountEffects (plugin:diarian:20052:11)
    at flushPassiveEffectsImpl (plugin:diarian:21433:11)
print @ plugin:diarian:30570
printToConsole @ plugin:diarian:30588
getNoteByMoment @ plugin:diarian:30668
imagePath @ plugin:diarian:41228
eval @ plugin:diarian:41243
commitHookEffectListMount @ plugin:diarian:18851
commitPassiveMountOnFiber @ plugin:diarian:20104
commitPassiveMountEffects_complete @ plugin:diarian:20072
commitPassiveMountEffects_begin @ plugin:diarian:20062
commitPassiveMountEffects @ plugin:diarian:20052
flushPassiveEffectsImpl @ plugin:diarian:21433
flushPassiveEffects @ plugin:diarian:21390
commitRootImpl @ plugin:diarian:21359
commitRoot @ plugin:diarian:21220
performSyncWorkOnRoot @ plugin:diarian:20838
flushSyncCallbacks @ plugin:diarian:11050
eval @ plugin:diarian:20570
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:203
runMicrotask @ node:internal/process/task_queues:137
```

Then this warning for the same notes
```
plugin:diarian:30570 [Diarian] warning: Could not get any notes with the date 2024-08-01T-03-43-00.
    at printToConsole (plugin:diarian:30545:11)
    at getNoteByMoment (plugin:diarian:30668:5)
    at imagePath (plugin:diarian:41228:26)
    at eval (plugin:diarian:41243:5)
    at commitHookEffectListMount (plugin:diarian:18851:34)
    at invokePassiveEffectMountInDEV (plugin:diarian:20267:19)
    at invokeEffectsInDev (plugin:diarian:21644:19)
    at commitDoubleInvokeEffectsInDEV (plugin:diarian:21629:15)
    at flushPassiveEffectsImpl (plugin:diarian:21446:13)
    at flushPassiveEffects (plugin:diarian:21390:22)
print @ plugin:diarian:30570
printToConsole @ plugin:diarian:30588
getNoteByMoment @ plugin:diarian:30668
imagePath @ plugin:diarian:41228
eval @ plugin:diarian:41243
commitHookEffectListMount @ plugin:diarian:18851
invokePassiveEffectMountInDEV @ plugin:diarian:20267
invokeEffectsInDev @ plugin:diarian:21644
commitDoubleInvokeEffectsInDEV @ plugin:diarian:21629
flushPassiveEffectsImpl @ plugin:diarian:21446
flushPassiveEffects @ plugin:diarian:21390
commitRootImpl @ plugin:diarian:21359
commitRoot @ plugin:diarian:21220
performSyncWorkOnRoot @ plugin:diarian:20838
flushSyncCallbacks @ plugin:diarian:11050
eval @ plugin:diarian:20570
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:203
runMicrotask @ node:internal/process/task_queues:137
```

And finally, this errors, three times each, probably one for each note (there are differences in the stack calls)
```
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'path')
    at t.<anonymous> (app.js:1:734072)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at app.js:1:236159
    at new Promise (<anonymous>)
    at v (app.js:1:235904)
    at t.read (app.js:1:733953)
    at t.<anonymous> (app.js:1:734315)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.read @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.cachedRead @ app.js:1
imagePath @ plugin:diarian:41229
eval @ plugin:diarian:41243
commitHookEffectListMount @ plugin:diarian:18851
commitPassiveMountOnFiber @ plugin:diarian:20104
commitPassiveMountEffects_complete @ plugin:diarian:20072
commitPassiveMountEffects_begin @ plugin:diarian:20062
commitPassiveMountEffects @ plugin:diarian:20052
flushPassiveEffectsImpl @ plugin:diarian:21433
flushPassiveEffects @ plugin:diarian:21390
commitRootImpl @ plugin:diarian:21359
commitRoot @ plugin:diarian:21220
performSyncWorkOnRoot @ plugin:diarian:20838
flushSyncCallbacks @ plugin:diarian:11050
eval @ plugin:diarian:20570
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:203
runMicrotask @ node:internal/process/task_queues:137
await in runMicrotask (async)
eval @ plugin:diarian:41243
commitHookEffectListMount @ plugin:diarian:18851
commitPassiveMountOnFiber @ plugin:diarian:20104
commitPassiveMountEffects_complete @ plugin:diarian:20072
commitPassiveMountEffects_begin @ plugin:diarian:20062
commitPassiveMountEffects @ plugin:diarian:20052
flushPassiveEffectsImpl @ plugin:diarian:21433
flushPassiveEffects @ plugin:diarian:21390
commitRootImpl @ plugin:diarian:21359
commitRoot @ plugin:diarian:21220
performSyncWorkOnRoot @ plugin:diarian:20838
flushSyncCallbacks @ plugin:diarian:11050
eval @ plugin:diarian:20570
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:203
runMicrotask @ node:internal/process/task_queues:137
````

```
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'path')
    at t.<anonymous> (app.js:1:734072)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at app.js:1:236159
    at new Promise (<anonymous>)
    at v (app.js:1:235904)
    at t.read (app.js:1:733953)
    at t.<anonymous> (app.js:1:734315)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.read @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.cachedRead @ app.js:1
imagePath @ plugin:diarian:41229
eval @ plugin:diarian:41243
commitHookEffectListMount @ plugin:diarian:18851
invokePassiveEffectMountInDEV @ plugin:diarian:20267
invokeEffectsInDev @ plugin:diarian:21644
commitDoubleInvokeEffectsInDEV @ plugin:diarian:21629
flushPassiveEffectsImpl @ plugin:diarian:21446
flushPassiveEffects @ plugin:diarian:21390
commitRootImpl @ plugin:diarian:21359
commitRoot @ plugin:diarian:21220
performSyncWorkOnRoot @ plugin:diarian:20838
flushSyncCallbacks @ plugin:diarian:11050
eval @ plugin:diarian:20570
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:203
runMicrotask @ node:internal/process/task_queues:137
await in runMicrotask (async)
eval @ plugin:diarian:41243
commitHookEffectListMount @ plugin:diarian:18851
invokePassiveEffectMountInDEV @ plugin:diarian:20267
invokeEffectsInDev @ plugin:diarian:21644
commitDoubleInvokeEffectsInDEV @ plugin:diarian:21629
flushPassiveEffectsImpl @ plugin:diarian:21446
flushPassiveEffects @ plugin:diarian:21390
commitRootImpl @ plugin:diarian:21359
commitRoot @ plugin:diarian:21220
performSyncWorkOnRoot @ plugin:diarian:20838
flushSyncCallbacks @ plugin:diarian:11050
eval @ plugin:diarian:20570
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:203
runMicrotask @ node:internal/process/task_queues:137
```

**Comment by ElsaTam** [comment]
@ElsaTam It still does, but not anymore with only one note.
So:
- If I have only one note in the daily note folder, I change the format name, then refresh -> ok
- If I have 36 notes in the daily note folder following the same format name, then refresh -> crash
I don't know when is the number of notes too high to create the crash. Or if it's really a matter of number of notes in the end...

**Comment by Erallie** [comment]
@ElsaTam I still can't manage to reproduce the issue... Are they the same errors that you're getting? And can you maybe send a video or something showing the issue being reproduced?

**Comment by ElsaTam** [comment]
https://drive.google.com/file/d/1kfccdHTwbnKahsTexwiX0_iYlL0Bqn-F/view?usp=sharing
Here is a Google Drive link, video was too big for GitHub.
Let me knows if it helps!
